// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RecipesGrpc.Migrations
{
    [DbContext(typeof(RecipesDbContext))]
    [Migration("20250106205944_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipesGrpc.Model.RecipeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CookTime")
                        .HasColumnType("integer");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrepTime")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookTime = 60,
                            Ingredients = "Свекла, капуста, картофель, морковь, лук, мясо, томатная паста",
                            Instructions = "Подготовить овощи, сварить мясной бульон, добавить овощи, приправить.",
                            Name = "Борщ",
                            PrepTime = 20
                        },
                        new
                        {
                            Id = 2,
                            CookTime = 10,
                            Ingredients = "Картофель, морковь, яйца, колбаса, солёные огурцы, зелёный горошек, майонез",
                            Instructions = "Отварить картофель, морковь и яйца, нарезать все ингредиенты, смешать с майонезом.",
                            Name = "Оливье",
                            PrepTime = 30
                        },
                        new
                        {
                            Id = 3,
                            CookTime = 15,
                            Ingredients = "Мука, яйца, вода, фарш (свинина и говядина), лук, специи",
                            Instructions = "Замесить тесто, сформировать пельмени с фаршем, отварить в кипящей воде.",
                            Name = "Пельмени",
                            PrepTime = 40
                        },
                        new
                        {
                            Id = 4,
                            CookTime = 30,
                            Ingredients = "Свинина, лук, уксус, соль, специи",
                            Instructions = "Замариновать мясо, нанизать на шампуры, обжарить на углях.",
                            Name = "Шашлык",
                            PrepTime = 240
                        },
                        new
                        {
                            Id = 5,
                            CookTime = 15,
                            Ingredients = "Мука, яйца, вода, картофель, лук, сливочное масло",
                            Instructions = "Замесить тесто, приготовить начинку из картофеля и лука, сформировать вареники, отварить.",
                            Name = "Вареники с картошкой",
                            PrepTime = 30
                        },
                        new
                        {
                            Id = 6,
                            CookTime = 20,
                            Ingredients = "Мука, молоко, яйца, сахар, соль, растительное масло",
                            Instructions = "Замесить тесто, жарить блины на сковороде.",
                            Name = "Блины",
                            PrepTime = 10
                        },
                        new
                        {
                            Id = 7,
                            CookTime = 240,
                            Ingredients = "Свиные ножки, говядина, лук, морковь, чеснок, специи",
                            Instructions = "Варить мясо до готовности, процедить бульон, добавить чеснок, разлить по формам и остудить.",
                            Name = "Холодец",
                            PrepTime = 30
                        },
                        new
                        {
                            Id = 8,
                            CookTime = 40,
                            Ingredients = "Копчёности, колбаса, мясо, картофель, солёные огурцы, томатная паста, маслины",
                            Instructions = "Обжарить копчёности, добавить овощи, сварить суп, украсить маслинами.",
                            Name = "Солянка",
                            PrepTime = 20
                        },
                        new
                        {
                            Id = 9,
                            CookTime = 60,
                            Ingredients = "Рис, мясо, морковь, лук, чеснок, специи",
                            Instructions = "Обжарить мясо с овощами, добавить рис, залить водой, готовить до готовности.",
                            Name = "Плов",
                            PrepTime = 20
                        },
                        new
                        {
                            Id = 10,
                            CookTime = 40,
                            Ingredients = "Курица, лапша, картофель, морковь, лук, специи",
                            Instructions = "Сварить курицу, добавить овощи и лапшу, варить до готовности.",
                            Name = "Куриный суп с лапшой",
                            PrepTime = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
