global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:80']

  - job_name: 'grpc-service'
    static_configs:
      - targets: ['grpc-service:50051']
